name: 'Update Static Assets'
description: 'Attempts to update the versions of static CDN assets in a repository.'
author: 'Martin Costello'
branding:
  icon: 'refresh-cw'
  color: 'blue'
inputs:
  repo-token:
    description: 'The GitHub access token to use to create a pull request for any updates to the repository.'
    required: true
  branch-name-prefix:
    description: 'The optional Git branch name prefix to use.'
    required: false
    default: ''
  close-superseded:
    description: 'If true, any existing pull requests superseded by any pull requests opened by the action are closed.'
    required: false
    default: true
  commit-message:
    description: 'The optional Git commit message to use.'
    required: false
    default: ''
  file-extensions:
    description: 'The optional comma-separated file extension(s) to search for static assets within.'
    required: false
    default: 'cshtml,html,razor'
  labels:
    description: 'The optional comma-separated label(s) to apply to pull requests generated by the action.'
    required: false
    default: ''
  repo:
    description: 'The optional GitHub repository to generate the pull request against.'
    required: false
    default: ${{ github.repository }}
  repo-path:
    description: 'The optional path of the repository to check for updates.'
    required: false
    default: ${{ github.workspace }}
  user-email:
    description: 'The optional email address to use for Git commits.'
    required: false
    default: 'github-actions[bot]@users.noreply.github.com'
  user-name:
    description: 'The optional user name to use for Git commits.'
    required: false
    default: 'github-actions[bot]'
  dry-run:
    description: 'If true, the action will not push changes to GitHub.'
    required: false
    default: false
outputs:
  assets-updated:
    description: 'Whether any static assets were updated by the action.'
  pulls-closed:
    description: 'A JSON array of the numbers of any pull requests that were closed as superseded.'
  pulls-opened:
    description: 'A JSON array of the numbers of any pull requests that were opened to update static assets.'
runs:
  using: 'node20'
  main: 'dist/main.js'
